{% set version = "0.97" %}

package:
  name: flexiplex
  version: {{ version }}

source:
        # url: https://github.com/DavidsonGroup/flexiplex/releases/download/Version-{{ version }}/flexiplex-Version-{{ version }}.tar.gz
        # git_url: https://github.com/DavidsonGroup/flexiplex.git
        path: ../

build:
  number: 0
  entry_points:
    - flexiplex-filter = flexiplex_filter.main:cli

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools  # to install flexiplex-filter
  run:
    - python
    - numpy
    - pandas
    - matplotlib

about:
  home: https://github.com/DavidsonGroup/flexiplex/
  license: MIT License
  summary: 'flexiplex: the flexible demultiplexer'
  license_family: MIT

