on: [push]

jobs:
  build:
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-x64
            container: quay.io/pypa/manylinux2014_x86_64
          - os: macos-14
            label: macos-arm64
          - os: macos-latest
            label: macos-x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make
        run: make

      - name: Add execute permission
        run: chmod +x ./flexiplex

      - name: Tar files
        run: tar -cvf ./result.tar ./flexiplex

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ steps.vars.outputs.sha_short }}-${{ matrix.label }}
          path: ./result.tar
          compression-level: 0
          retention-days: 90
