on: [push]

jobs:
  build:
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'src'
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: 3.8
          use-only-tar-bz2: true # for caching
      - name: Install conda-build
        run: conda install conda-build
      - name: Build package
        run: conda build conda-recipe
        working-directory: src/
