on: [push]

jobs:
  build:
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-x64
          - os: macos-14
            label: macos-arm64
          - os: macos-latest
            label: macos-x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make
        run: make

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}-${{ matrix.label }}
          path: ./flexiplex
          retention-days: 90
